### PR TITLE
SQLite3 Support

### PR DESCRIPTION
**Pull request by Zhomart**
All default tests pass.

### CODE REVIEW

**Comment by fridgerator** [comment]
Great work @Zhomart !!

Seems like its just a matter of getting travis to play nicely

**Comment by Zhomart** [comment]
Alright, fixed!

**Comment by fridgerator** [comment]
Awesome dude!  Much appreciated!

**Comment by fridgerator** [comment]
out of curiosity, what changes are in your fork of crystal-sqlite3?

**Comment by Zhomart** [comment]
This PR https://github.com/crystal-lang/crystal-sqlite3/pull/19

There were issues with `::DB::ResultSet#read(Int32 | Nil)` and with type `Time`.
Issue with time was traced back to crystal language https://github.com/crystal-lang/crystal/issues/4176

**Comment by fridgerator** [comment]
thanks

**Comment by duraki** [comment]
Awesome work @Zhomart.

**Pull request merged**
